### ISSUE TITLE
Your private key is compromised

### ISSUE THREAD

**Issue by SimonSapin** [arcnmx/youmu-docs#5]
https://github.com/arcnmx/youmu-docs/blob/51ac9205ac227d745ca224b082cfea8b86af2eb6/.travis/id is public. Is it encrypted? I don’t see any private environment variable in Travis-CI builds that indicate that it is. Unless it is, you should consider it compromised. Revoke any access it has, and generate a new on.

http://docs.travis-ci.com/user/encrypting-files/ is a way to have encrypted files that only Travis-CI knows how to read. More info on this approach: https://github.com/kmcallister/travis-doc-upload/blob/master/README.md

Alternatively, using a GitHub "personal access token" in a secure Travis-CI environment variable may be easier: https://github.com/tomprogrammer/rust-ascii/issues/10#issuecomment-126090353

**Comment by arcnmx** [comment]
This is intentional, actually. It's a deploy key that gives access to this repo because I don't have infrastructure set up to do this myself - I kind of just bootstrapped this whole thing off of Travis because it was the simplest approach I came up with to get a prototype up. The repo is set up to auto-accept any PRs that get submitted to it.

Putting together a proper web service for submissions instead would be a lot nicer!

**Comment by arcnmx** [comment]
(sorry if that response/close seemed dismissive, I just don't want to make it _too_ obvious that the key is there or what it's for. It's certainly an issue that should get resolved.)

**Comment by SimonSapin** [comment]
No worries, as long as it’s intentional :)
